### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LeilyR** [deeptools/Knight-Ruiz-Matrix-balancing-algorithm#4]
- [x] passing a sparse matrix by reference instead of copying it, 

- [ ] changed the double to float for the output matrix,

- [ ] documentation,

- [x] list of dependencies
